language: python
python:
  - 3.8.2
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8 .
  - pipenv run pytest
  - pytest --cov=curso_django
after_success:
  -codecov
